"""Auto migration

Revision ID: 0bebeb2150a2
Revises: b197fc0db1e6
Create Date: 2025-05-14 01:56:30.883162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bebeb2150a2'
down_revision = 'b197fc0db1e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_expire_range', sa.String(length=16), nullable=True))
        batch_op.drop_column('alert_frequency')
        batch_op.drop_column('alert_threshold')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_threshold', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('alert_frequency', sa.VARCHAR(length=16), nullable=True))
        batch_op.drop_column('share_expire_range')

    # ### end Alembic commands ###
