"""Auto migration

Revision ID: 50d64ee7b335
Revises: 62b8f2ca88f0
Create Date: 2025-05-07 02:15:23.579092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d64ee7b335'
down_revision = '62b8f2ca88f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('fuel_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_fuel_prices_batch_id'), ['batch_id'], unique=False)
        batch_op.create_foreign_key(None, 'upload_batches', ['batch_id'], ['id'])
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_fuel_prices_batch_id'))
        batch_op.drop_column('batch_id')

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('verified', sa.BOOLEAN(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('is_social_login', sa.BOOLEAN(), nullable=True),
    sa.Column('avatar', sa.VARCHAR(length=256), nullable=True),
    sa.Column('email_verify_code', sa.VARCHAR(length=6), nullable=True),
    sa.Column('email_verify_expiration', sa.DATETIME(), nullable=True),
    sa.Column('default_fuel_type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('default_date_range', sa.VARCHAR(length=16), nullable=True),
    sa.Column('default_location', sa.VARCHAR(length=64), nullable=True),
    sa.Column('alert_threshold', sa.FLOAT(), nullable=True),
    sa.Column('alert_frequency', sa.VARCHAR(length=16), nullable=True),
    sa.Column('public_dashboard', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
