"""Auto migration

Revision ID: 62b8f2ca88f0
Revises: 6c47205a80fc
Create Date: 2025-05-06 15:19:50.021703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b8f2ca88f0'
down_revision = '6c47205a80fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_fuel_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('default_date_range', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('default_location', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('alert_threshold', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('alert_frequency', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('public_dashboard', sa.Boolean(), nullable=True))
        batch_op.alter_column('avatar',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('email_verify_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=6),
               existing_nullable=True)
        batch_op.alter_column('email_verify_expiration',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email_verify_expiration',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email_verify_code',
               existing_type=sa.String(length=6),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('avatar',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('public_dashboard')
        batch_op.drop_column('alert_frequency')
        batch_op.drop_column('alert_threshold')
        batch_op.drop_column('default_location')
        batch_op.drop_column('default_date_range')
        batch_op.drop_column('default_fuel_type')

    # ### end Alembic commands ###
