"""Auto migration

Revision ID: 8144e3cb1fcf
Revises: 84f6e9ba8244
Create Date: 2025-05-12 15:29:17.052153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8144e3cb1fcf'
down_revision = '84f6e9ba8244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_price_records_batch_id'), ['batch_id'], unique=False)
        batch_op.create_foreign_key('fk_fuelprices_batch_id', 'upload_batches', ['batch_id'], ['id'])

    with op.batch_alter_table('upload_batches', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=200), nullable=True))

    with op.batch_alter_table('price_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_price_records_batch_id'))
        batch_op.drop_column('batch_id')

    # ### end Alembic commands ###
