"""Auto migration

Revision ID: 84f6e9ba8244
Revises: 50d64ee7b335
Create Date: 2025-05-12 15:22:17.331650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f6e9ba8244'
down_revision = '50d64ee7b335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_prices', schema=None) as batch_op:
        batch_op.drop_index('ix_fuel_prices_batch_id')
        batch_op.drop_index('ix_fuel_prices_publish_date')
        batch_op.drop_index('ix_fuel_prices_region_description')

    op.drop_table('fuel_prices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_prices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('batch_id', sa.INTEGER(), nullable=False),
    sa.Column('publish_date', sa.DATE(), nullable=False),
    sa.Column('trading_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('brand_description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('product_description', sa.VARCHAR(length=100), nullable=False),
    sa.Column('product_price', sa.FLOAT(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('postcode', sa.VARCHAR(length=20), nullable=True),
    sa.Column('area_description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('region_description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batches.id'], name='fk_fuelprices_batch_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_prices', schema=None) as batch_op:
        batch_op.create_index('ix_fuel_prices_region_description', ['region_description'], unique=False)
        batch_op.create_index('ix_fuel_prices_publish_date', ['publish_date'], unique=False)
        batch_op.create_index('ix_fuel_prices_batch_id', ['batch_id'], unique=False)

    # ### end Alembic commands ###
