"""Auto migration

Revision ID: b197fc0db1e6
Revises: 8144e3cb1fcf
Create Date: 2025-05-13 04:49:42.851075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b197fc0db1e6'
down_revision = '8144e3cb1fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_shares')
    with op.batch_alter_table('shared_report', schema=None) as batch_op:
        batch_op.drop_column('comparison_config')
        batch_op.drop_column('trend_config')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trend_config', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('comparison_config', sa.TEXT(), nullable=True))

    op.create_table('data_shares',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('batch_id', sa.INTEGER(), nullable=False),
    sa.Column('shared_to_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batches.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'batch_id', 'shared_to_id', name='uq_share_owner_batch_user')
    )
    # ### end Alembic commands ###
