name: Frontend Linting

on:
  push:
    paths:
      - "app/frontend/js/**/*.js"
      - "app/frontend/css/**/*.css"
      - "app/templates/**/*.html"
  pull_request:
    paths:
      - "app/frontend/js/**/*.js"
      - "app/frontend/css/**/*.css"
      - "app/templates/**/*.html"

jobs:
  lint:
    name: Lint Frontend Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js (for CLI linters)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Global Linters
        run: |
          npm install -g eslint stylelint stylelint-config-standard htmlhint

      - name: Run ESLint (JS) if any .js file exists
        run: |
          if find app/frontend/js -name "*.js" | grep -q .; then
            echo "Running ESLint..."
            eslint app/frontend/js/**/*.js
          else
            echo "No JS files found, skipping ESLint."
          fi

      - name: Run Stylelint (CSS) if any .css file exists
        run: |
          if find app/frontend/css -name "*.css" | grep -q .; then
            echo "Running Stylelint..."
            stylelint app/frontend/css/**/*.css
          else
            echo "No CSS files found, skipping Stylelint."
          fi

      - name: Run HTMLHint (HTML) if any .html file exists
        run: |
          if find app/templates -name "*.html" | grep -q .; then
            echo "Running HTMLHint..."
            htmlhint app/templates/**/*.html
          else
            echo "No HTML files found, skipping HTMLHint."
          fi
