name: Frontend Linting

on:
  push:
    paths:
      - "app/frontend/js/**/*.js"
      - "app/frontend/css/**/*.css"
      - "app/templates/**/*.html"
  pull_request:
    paths:
      - "app/frontend/js/**/*.js"
      - "app/frontend/css/**/*.css"
      - "app/templates/**/*.html"

jobs:
  lint:
    name: Lint Frontend Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js (for CLI linters)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Global Linters
        run: |
          npm install -g eslint stylelint stylelint-config-standard htmlhint

      - name: Run ESLint (JS)
        run: |
          eslint app/frontend/js/**/*.js || exit 1

      - name: Run Stylelint (CSS)
        run: |
          stylelint app/frontend/css/**/*.css || exit 1

      - name: Run HTMLHint (HTML)
        run: |
          htmlhint app/templates/**/*.html || exit 1
