name: Frontend Linting

on:
  push:
    paths:
      - "app/static/js/**/*.js"
      - "app/static/css/**/*.css"
      - "app/templates/**/*.html"
  pull_request:
    paths:
      - "app/static/js/**/*.js"
      - "app/static/css/**/*.css"
      - "app/templates/**/*.html"

jobs:
  lint:
    name: Lint Frontend Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js (for JS/CSS linters)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Global Linters (ESLint & Stylelint)
        run: |
          npm install -g eslint@8.56.0

      - name: Install Python and djlint
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install djlint
        run: |
          pip install djlint

      - name: Run ESLint (JS) if any .js file exists
        run: |
          if find app/static/js -name "*.js" | grep -q .; then
            echo "Running ESLint..."
            eslint app/static/js/**/*.js
          else
            echo "No JS files found, skipping ESLint."
          fi

      - name: Run djlint (Jinja2/HTML) if any .html file exists
        run: |
          if find app/templates -name "*.html" | grep -q .; then
            echo "Running djlint..."
            djlint app/templates/
          else
            echo "No HTML files found, skipping djlint."
          fi
